name: libsemigroups-docs

channels:
  - anaconda
  - conda-forge
  - eumetsat

dependencies:
  - breathe
  - beautifulsoup4
  - doxygen
  - expect
  - lxml 
  - sphinx
  - sphinx_rtd_theme 
  - sphinx-copybutton 
  - sphinxcontrib-bibtex
